### ISSUE TITLE
Print line number of failed command

### ISSUE THREAD

**Issue by jaebaek** [google/amber#113]
Currently, Amber prints the line number of a command that causes parsing errors but it does not print the one that causes other program failures e.g., failures from probe, failures from vulkan.

It would be difficult to quickly find which line causes errors in the view of script writers.

**Comment by dj2** [comment]
I'm not sure if this needs line numbers, it just needs context. If we say 1 != 1, that doesn't help much, but if we output something like: probe x y z != a b c, would make it pretty easy for them to match up the results I think.

Having line numbers are possible, but more tricky I think

**Comment by jaebaek** [comment]
Let's regard it as a lower priority issue and discuss it later.

**Comment by dj2** [comment]
What are the errors which are output for the above. Is it parse errors, execution error, what goes wrong? The AmberScript parser does line numbers, it should be easy to do in the parser for VkScript at this point.

**Comment by jaebaek** [comment]
The error message is `Invalid value provided to probe ssbo  command` and which is from line 452 of src/vkscript/command_parser.cc

It is a parse error
