### ISSUE TITLE
Add Vulkan pipeline cache

### ISSUE THREAD

**Issue by jaebaek** [google/amber#131]
This might improve performance.
See [Vulkan pipeline cache](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#pipelines-cache).

**Comment by dj2** [comment]
I don't think we should do this until we have a performance issue we're facing. The cache will just add complexity at this point.

**Comment by dj2** [comment]
I don't think this is something we're going to need. We don't really know ahead of time how our pipelines can be shared, and we don't want to share over runs I think.
