### ISSUE TITLE
Error from discontinuous descriptor sets

### ISSUE THREAD

**Issue by jaebaek** [google/amber#158]
Amber supports descriptors with consecutive descriptor sets from `[0, N]`, but it does not support discontinuous descriptor sets e.g., `1, 3, 5`.

**Comment by dj2** [comment]
This is specifically the Vulkan backend, yea? I don't think there is anything in the parser/executor which would have an issue here.

**Comment by jaebaek** [comment]
This is for Vulkan backend, not parser nor executor.
