### ISSUE TITLE
BufferType::kFramebuffer is not needed

### ISSUE THREAD

**Issue by jaebaek** [google/amber#190]
Frame buffer can have images for color output and depth/stencil output.
`BufferType::kColor` and `BufferType::kDepth` are enough for frame buffer and `BufferType::kFramebuffer` is not needed.

**Comment by jaebaek** [comment]
@dj2 Could you please doublecheck if I understand it correctly?

**Comment by dj2** [comment]
The buffer types are all invalid at this point. The document has been updated but I haven't caught up with the code yet. I'll get to it when I get back to updating the code to match the design doc.

**Comment by dj2** [comment]
This is fixed kFramebuffer no longer exists.
