### ISSUE TITLE
Default memory layout and explicit memory layout setup for Amber script

### ISSUE THREAD

**Issue by jaebaek** [google/amber#193]
I suggest that Amber script uses the same layouts for SSBO, UBO, and push constant as glslang does in default.
In addition, we should support explicit setup for memory layouts.

[glslang](https://github.com/KhronosGroup/glslang) compiles layout of SSBO / push constant as `std430` and UBO as `std140`.

See the following example and [Vulkan memory layout spec](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#interfaces-resources-layout) for more details,

```
#version 450

// push_constant compiled as std430 by glslang
layout(push_constant) uniform block {
  float a[3];   // Offset: 0
  int b;        //        12
  vec3 c;       //        16
  int d;        //        28
  float e[3];   //        32
  int f;        //        44
} b0;

// SSBO compiled as std430 by glslang
layout(set = 0, binding = 0) buffer block1 {
  float a[3];   // Offset: 0
  int b;        //        12
  mat4 c;       //        16
  int d[5];     //        80
  float e;      //       100
} b1;

// UBO compiled as std140 by glslang
layout(set = 0, binding = 1) uniform block2 {
  float a[3];   // Offset: 0
  int b;        //        48
  mat4 c;       //        64
  int d[5];     //       128
  float e;      //       208
} b2;

void main() {
}
```

**Comment by dj2** [comment]
Can you give an example of what you mean by explicit memory layout?

**Comment by dneto0** [comment]
We've done enough here for now.
