### ISSUE TITLE
Line number report on error

### ISSUE THREAD

**Issue by jaebaek** [google/amber#195]
```
[compute shader]
#version 430

void main() {
}

[test]
# Error must report "9: Unknown command: unknown"
unknown
```

`unknown` is in line 9, but it reports "8: Unknown command: unknown"

**Comment by dj2** [comment]
Yes, that's a know issue and i'm not sure if it's worth fixing. The parser as already consumed the \n which means the line number increases. Then we process the unknown so it's off slightly.

**Comment by dj2** [comment]
Oh, I think i read that backwards you're saying it's too low not to high? Is it the comment that throws it off?

**Comment by jaebaek** [comment]
If I remove the comment,

```
[compute shader]
#version 430

void main() {
}

[test]
unknown
```
must report `8: Unknown command: unknown` but the actual error message is `7: Unknown command: unknown`.

It correctly reports the line number if an error happens before `[compute shader]` section.

For example,

```

unknown
[compute shader]
#version 430

void main() {
}

[test]
compute 1 1 1
```

reports `2: Unknown command: unknown`, which is what we expect.

**Comment by dj2** [comment]
This no longer reproduces. Adding a test case to show as much.
