### ISSUE TITLE
Check or manage image layout inside Image class

### ISSUE THREAD

**Issue by jaebaek** [google/amber#209]
Currently, image layout is changed by `Image::ChangeLayout()` and external components of Image class calls it to manage the layout. This might be confusing and we need to explicitly check or manage image layout inside Image class. Currently, we use Image only for Framebuffer and it is fine, but it would be buggy when we support image based descriptors.

**Comment by dj2** [comment]
Note, Image is now called TransferImage as it's used to transfer data from the CPU -> GPU and back.

**Comment by dj2** [comment]
Actually, I'm going to close this as we don't need to do anything at the moment. When we do image descriptors we'll fix anything needed when it comes up.
