### ISSUE TITLE
Pass VkPhysicalDeviceProperties when reusing VkDevice

### ISSUE THREAD

**Issue by jaebaek** [google/amber#213]
[Vulkan CTS](https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/modules/vulkan/vktTestCase.hpp) provides `VkPhysicalDeviceProperties` via `const vk::VkPhysicalDeviceProperties&		getDeviceProperties				(void) const;`.
We should pass it to Amber to check
```
    uint32_t              maxUniformBufferRange;
    uint32_t              maxStorageBufferRange;
    uint32_t              maxPushConstantsSize;
```

**Comment by dj2** [comment]
Is this still needed? The CTS integration seems to be working at this point.

**Comment by dj2** [comment]
Closing this for now as it doesn't seem required. We can revisit later if desired.
