### ISSUE TITLE
Improve error report

### ISSUE THREAD

**Issue by jaebaek** [google/amber#219]
Currently, we do not provide users with the line number of failure.

For example, if `(A)` has a problem in the following code,
```
probe ssbo int 0  0 == 0
probe ssbo int 0  4 == 2
probe ssbo int 0 16 == 4    # (A)
```
Amber says `...: Verifier failed: 4.000000 == 0.000000, at index 0`.
This does not let users know which line has problem.
In addition, printing `offset` from the buffer is more clear than `index`.

**Comment by jaebaek** [comment]
@dj2 could you please check this?

**Comment by dj2** [comment]
I don't think we want to change index to be the offset, as you can have multiple values and it's telling you which of those multiple values failed.
