### ISSUE TITLE
Support Vulkan 1.1

### ISSUE THREAD

**Issue by jaebaek** [google/amber#220]
Currently, VkRunner spec says it will support only Vulkan 1.0 and Amber also supports only Vulkan 1.0 for VkRunnerScript.

There would be many use cases to test with Vulkan 1.1.
It would be nice if we provide a commend to set the Vulkan version in AmberScript.

**Comment by dj2** [comment]
This seems like it should be a in the requires section of vkscript:
```
[require]
engine vulkan 1.1
```
Will probably work. Then we just need plumb it through to the engine. This would allow us to say:

```
engine vulkan
engine vulkan 1.0
engine vulkan 1.1
engine dawn
```

then we skip that test if we're running with a different/ incompatible engine.

**Comment by dj2** [comment]
@alan-baker does this seem like it would cover what you needed?

**Comment by dj2** [comment]
We have a command line flag to set the vulkan version now, but there is more work to be done in order to handle different property flags.

**Comment by dj2** [comment]
I'm going to close this as I don't think we need to do this anymore. You can provide different features/extensions as needed and you can give a command line option to turn on vulkan 1.1. The scripts themselves should be backwards compatible with previous extensions to all degrees possible.

If we find there is a script we just can't write, we can re-open this issue.
