### ISSUE TITLE
Enable specification of spirv version

### ISSUE THREAD

**Issue by alan-baker** [google/amber#221]
Currently amber uses Vulkan 1.0 to assemble SPIR-V. It would be useful to be able to specify the SPIR-V version to use (e.g. Vulkan 1.1) as a SPIR-V/Vulkan version.

I would suggest extending the shader declaration to specify the shader version.

**Comment by dj2** [comment]
Have to be able to support multiple SPIR-V versions in a single script. So, each thing we assemble/verify will need a new spirv-tools for that given version.

**Comment by dj2** [comment]
CL #273 allows setting the spirv environment from the command line. I think that's as far as we need to take this at this point. We don't have need to do multiple spirv versions in a single file at this point.
