### ISSUE TITLE
Memory leaks in amber

### ISSUE THREAD

**Issue by s-perron** [google/amber#277]
`EngineConfig` does not have a virtual destructor, so `VulkanEngineConfig` do not get destroyed properly.

In `PushConstant::PushConstant`, an array of uint8_t is allocated, but the pointer is kept in a unique_ptr<uint8_t>.

I found these using ASAN.  There is another leak reported, but it is very confusing.  I cannot tell where it comes from.

**Comment by dj2** [comment]
@dneto0 has a CL for the virtual destructor.

@jaebaek can you look into the PushConstant code when you get back? Can we use a vector instead of an array?

**Comment by dneto0** [comment]
My CL got into trouble.  I've stopped looking at it.

**Comment by dj2** [comment]
Fixed.
