### ISSUE TITLE
what state is reset between Engine::CreatePipeline ?

### ISSUE THREAD

**Issue by dneto0** [google/amber#288]
Raised by this review comment: https://github.com/google/amber/pull/286#discussion_r256134615

The depth/stencil buffer is optional.  So what happens if the first pipeline sets depth/stencil and the second pipeline doesn't want it?

More generally, what about vertex buffers, index buffers, framebuffer.  Or clear colour, clear depth, clear stencil.

**Comment by dj2** [comment]
Each pipeline specifies their framebuffers, depth buffers, vertex buffers, etc. All of the CreatePipeline commands will be run at the beginning of the script before any commands are set. This should setup the internal pipeline stuffs.

As each Command is executed, a pipeline will be attached. The engine needs to setup that pipeline as the current one then execute the command. This would mean things like RUN and CLEAR COLOR will be against a specific pipeline.
