### ISSUE TITLE
Support OpenCL-C as a shader type

### ISSUE THREAD

**Issue by dj2** [google/amber#29]
Add support for OPENCL-C shaders, probably through [clspv](https://github.com/google/clspv).

**Comment by dj2** [comment]
This needs to both compile the shader through CLSPV but also retrieve the binding information back from the compiler and make it available to the pipeline.

**Comment by alan-baker** [comment]
#574 added basic support for the shader format, but the descriptor map is not parsed.

**Comment by alan-baker** [comment]
#584 Parses the descriptor map.
