### ISSUE TITLE
Provide link to sample in README

### ISSUE THREAD

**Issue by afd** [google/amber#292]
The Amber README has a section called "Amber Sample", but this section doesn't actually point the reader to a sample script file they could try.

After:

"
The build will generate an out/Debug/amber executable which can be used to run amber scripts. The script can be used as out/Debug/amber <path to amber file>. Where, currently, the amber file is in the VkScript format.
"
it would be nice to have an example command pointing to some specific amber file in the repo, with an expected output.

**Comment by dj2** [comment]
There are tests in tests/cases which we can use for this purpose.
