### ISSUE TITLE
Amber gives a helpful error when an SSBO probe's offset is bad, but not when a bad offset is used to set an SSBO value

### ISSUE THREAD

**Issue by afd** [google/amber#296]
Amber gives a nice error when I run it on [this file](https://github.com/google/amber/files/2864971/good_error.amber.txt), telling me that I'm probing using an offset that is not a multiple of the data type size.

But for [this file](https://github.com/google/amber/files/2864970/bad_no_error.amber.txt) I get no equivalent error when I set an SSBO value using an offset that is not a multiple of the size of the type.

I think it would be great to have an error in both case, as thinking of offsets in terms of element counts rather than bytes is an easy mistake to make.

**Comment by dj2** [comment]
Ok, so for the bad case, we'd have to write ssbo 0:0 subdata int 4 subdata or some other multiple of sizeof(int).

We should be able to fix that up. Thanks for reporting.
