### ISSUE TITLE
Allow framebuffer width and height to be specified as command-line options

### ISSUE THREAD

**Issue by afd** [google/amber#311]
Currently for an image test, the framebuffer width and height are fixed to 250 by kFramebufferWidth and kFramebufferHeight.

I would like to be able to use different widths and heights, and I imagine this could be useful in general.

How about command-line options --framebuffer-width and --framebuffer-height that will override these defaults?

**Comment by dj2** [comment]
VkScript has an fbsize 256 256 [require] setting you can use. Would that work or do you need different framebuffer sizes for a single script and don't want to edit the file?

**Comment by afd** [comment]
Ah, didn't know about that - it would suit my needs perfectly, thanks.

I see #12 is open for this, but is labeled enhancement.  It would be really useful to have it.

**Comment by dj2** [comment]
Heh, it's an enhancement to amber. Let me see what I can get running. I'm going to close this in favour of #12.
