### ISSUE TITLE
Update -V to dump engine specific information as well as compilation information

### ISSUE THREAD

**Issue by dj2** [google/amber#323]
For the Vulkan engine we want to output at least the information from the physical device properties. Things like:

apiVersion: 1.1.85
driverVersion: 2148896768
vendorID: 20803
deviceID: 84148225
deviceName: Device Blah 123

**Comment by dj2** [comment]
@hevrard is there other information you'd like to see then these bits, or are they enough to get us started?

**Comment by hevrard** [comment]
I think this is enough for a start, asking for info outside of the ones available via the graphics API (e.g. the phone name on Android) is going to be out-of-scope for Amber.
