### ISSUE TITLE
create AmberScript sample showing image processing flow

### ISSUE THREAD

**Issue by dneto0** [google/amber#327]
I'm not sure if all the features are planned yet, but I'd like to support a script like this:

  First pipeline:  Fills one or more images with preprogrammed data.

  Second pipeline:  An image processing kernel (e.g. blur).  This is the actual intended "shader under test"

  Third pipeline:  Render the image to an output framebuffer.  (So we can write it out with "amber -i foo.png")

This way we can test image processing flows without having to read image files.

**Comment by asuonpaa** [comment]
I had a similar feature request in mind, but for graphics pipeline: the first pipeline renders something to a color buffer and the second would use that as an input texture. I'd be more than happy to contribute as it would open up lots of opportunities when using Amber in Vulkan CTS.

I'm seeing several issues related to image support. Would someone explain what's the current status for this work, and what I could do to help?

**Comment by dj2** [comment]
This should all be possible now. You can have multiple pipelines and you can pass buffers between them. So, for the example you provide, someone just needs to create a .amber file (we have to use the AmberScript format for this) to show generating an image in one pipeline and then using it as an image in the second pipeline.

I haven't worked with images in Vulkan yet, when you attach them to the pipeline, are they just buffers or do you need to setup something more then a buffer? If so, we need to figure out some syntax to handle that, and I'd need to see an example of what we need to do.

**Comment by asuonpaa** [comment]
Textures would work pretty much the same way the frame buffer does right now. It's a VkImage object with a view provided by VkImageView. But instead of using the image view as an attachment, the texture would be accessed using a descriptor like, for example, an ssbo would. The descriptor type would be a combined image sampler. Here's a  [Vulkan tutorial]( https://vulkan-tutorial.com/Texture_mapping/Combined_image_sampler) for that. Buffers can be used to copy data to and from the texture image the same way as with frame buffer.

My requirement for texture support is based on a CTS test I'm working on. There I would need to access different mip levels based on a vertex ID. So I'd need a way to specify how many mip levels the texture has. And in this case each level needs to be cleared to a different color. Someone else might use autogenerated mip levels, or maybe a pipeline that would bind a specific mip level as a frame buffer. In fact a graphics pipeline could be used for generating the regular mip maps where each level has a scaled down version of the previous level. Just specify correct size and level of the mip map and draw a filtered texture there.


Below is a draft amber file which shows how I would be using the texture support.

```
SHADER vertex vert_shader_clear PASSTHROUGH

SHADER fragment frag_shader GLSL
#version 430

layout(location = 0) in vec4 color_in;
layout(location = 0) out vec4 color_out;

void main() {
  color_out = color_in;
}
END

SHADER vertex vert_shader_lod GLSL
#version 430

layout(location = 0) in vec3 position_in;
layout(location = 0) in vec4 color_out;
layout(set = 0, binding = 0) uniform highp sampler2D u_sampler;

void main() {
  gl_Position = vec4(position_in, 1.0);
  // Pick a color from the center of a mipmap. Each corner point gets its own mip level.
  color_out = vec4(textureLod(u_sampler, vec2(0.5), float(gl_VertexIndex % 4)));
}
END

# New feature: specify the number of mip levels
BUFFER texture FORMAT R8G8B8A8_UNORM MIPLEVELS 4
BUFFER framebuffer FORMAT R8G8B8A8_UNORM

PIPELINE graphics clear_pipeline
  ATTACH vert_shader_clear
  ATTACH frag_shader
  FRAMEBUFFER_SIZE 512 512
  BIND BUFFER texture AS color LOCATION 0
END

PIPELINE graphics draw_pipeline
  ATTACH vert_shader_lod
  ATTACH frag_shader
  FRAMEBUFFER_SIZE 512 512
  # New feature: bind as texture. For Vulkan that would be combined image sampler.
  BIND BUFFER texture AS texture DESCRIPTOR_SET 0 BINDING 0
  BIND BUFFER framebuffer AS color LOCATION 0
END

CLEAR_COLOR clear_pipeline 255 0 0 255
# New feature: Specify which mip level to clear
CLEAR clear_pipeline MIPLEVEL 0

CLEAR_COLOR clear_pipeline 0 255 0 255
CLEAR clear_pipeline MIPLEVEL 1

CLEAR_COLOR clear_pipeline 0 0 255 255
CLEAR clear_pipeline MIPLEVEL 2

CLEAR_COLOR clear_pipeline 255 255 0 255
CLEAR clear_pipeline MIPLEVEL 3

RUN draw_pipeline DRAW_RECT POS 0 0 SIZE 512 512
 
# Check corners of the frame buffer: each should have a color from a different mip level.
EXPECT framebuffer IDX 0   0   SIZE 1 1 EQ_RGBA 255 0   0   255
EXPECT framebuffer IDX 511 0   SIZE 1 1 EQ_RGBA 0   255 0   255
EXPECT framebuffer IDX 511 511 SIZE 1 1 EQ_RGBA 0   0   255 255
EXPECT framebuffer IDX 0   511 SIZE 1 1 EQ_RGBA 255 255 0   255
```

**Comment by dj2** [comment]
For MIP levels, are they per texture or per pipeline? Could I have two pipelines and attach the same `BUFFER texture` but provide different mip levels?

**Comment by asuonpaa** [comment]
They are per texture.

**Comment by dj2** [comment]
If we did:

```groovy
BIND BUFFER texture AS texture MIP_LEVELS 4 DESCRIPTOR_SET 0 BINDING 0
```

that means we keep the texture knowledge together, we don't have to tell the buffer anything about textures in this case, we store the mip level in the binding information. Would that work?

What are the valid valids for `MIP_LEVELS` something like `<number>` or `AUTO`?

**Comment by asuonpaa** [comment]
I suppose that would work. Kind of like what you're doing when specifying the framebuffer size for the pipeline and not for the buffer.

MIP_LEVELS would be an unsigned integer. I'm not sure if <number> takes also decimals.

**Comment by dj2** [comment]
Awesome, yea keeps it similar to framebuffer size. Let's go with numbers for now as the MIPS_LEVEL and we can add something like AUTO later if there is a need for it.

**Comment by dj2** [comment]
Do we need to do the sampler work for this? Or can textures and samplers be done separately?

We'd originally discussed a syntax similar to `BIND SAMPLER {sampler_name} DESCRIPTOR_SET _id_ BINDING _id_` to handle samplers, does that get superceded by this, is it a subset or is it just different?

@dnovillo @ben-clayton

**Comment by dj2** [comment]
#417 is the issue around parsing the `SAMPLER` modifier.

**Comment by dnovillo** [comment]
I think it's fine to split the work up.

**Comment by dj2** [comment]
Sorry my question is, can the work be split up? Does adding textures make sense without adding samplers? (This is my lack of graphics knowledge showing)

**Comment by dnovillo** [comment]
Ah!  I believe the answer is "yes", but I am not 100% sure.  I'm also playing by ear since I don't have actual knowledge.  @alan-baker @dneto0 ?

**Comment by alan-baker** [comment]
You could test storage images if you didn't have samplers.

**Comment by asuonpaa** [comment]
You cannot test samplers without having some image to sample from, but like Alan said images can be tested without samplers.

**Comment by dj2** [comment]
Awesome, so we do this one first, once it lands we can handle samplers in a later CL. We can also handle loading images from disks in a later CL as this can use images generated in a prior pipeline.

**Comment by dj2** [comment]
We probably also want to set this up so:

```
BIND BUFFER texture AS texture DESCRIPTOR_SET 0 BINDING 0
```

works as well and sets mips level to `auto` or something similar.

**Comment by dj2** [comment]
is mips level a function of the texture or the sampler?

**Comment by dj2** [comment]
Answering my own question, in vulkan it's set as part of the image creation information. So, it's a texture function.

**Comment by asuonpaa** [comment]
If we did

`BIND BUFFER texture AS texture DESCRIPTOR_SET 0 BINDING 0`

how do we differentiate between storage image and a sampled texture? Do you think adding SAMPLER keyword to the same line like below would work?

`BIND BUFFER texture AS texture SAMPLER {sampler} DESCRIPTOR_SET 0 BINDING 0`

That would make it a combined image sampler descriptor in Vulkan. And if we use a separate `BIND SAMPLER` it would work as a standalone sampler which is also supported by Vulkan.

Do we already have an issue for adding for that `AS texture` part? I think that would be the first step in adding texture support.

**Comment by dj2** [comment]
This issue is for adding the AS texture part. The SAMPLER bug is #417. The original idea for samplers is in the amber_script.md file.

```
  # Bind the sampler at the given descriptor set and binding.
  BIND SAMPLER {sampler_name} DESCRIPTOR_SET _id_ BINDING _id_
```

but I also know there are multiple samplers in Vulkan, so we may need to change that to accommodate.

The `BIND AS texture` was specifically binding the image to use without a sampler. Adding the `SAMPLER` maybe better then the `BIND SAMPLER` above.

Either way, let's get `As texture` done first, which binds without a sampler and then we can extend to add sampler support afterwards.

**Comment by asuonpaa** [comment]
Multiple samplers isn't a problem with this syntax since they all have separate bindings. And we can always interpret texture and sampler binding for the same binding slot to mean a combined image sampler. What I'm saying is we don't necessarily need to have all in one line after all.

**Comment by asuonpaa** [comment]
@dj2 can you assign this issue to me?

**Comment by afd** [comment]
@asuonpaa I've done the assignment (kept @dj2 as an assignee too for now).

**Comment by dj2** [comment]
We have #417 to mark things as samplers. So, does it make sense that a texture, which isn't bound as a sampler is a storage texture?  This issue focues on the storage texture, then we do #417 to handle samplers.

**Comment by asuonpaa** [comment]
We still wouldn't know if the texture is a storage image or a sampled image. Either of those don't have a sampler bound.

**Comment by asuonpaa** [comment]
To be clear we might have a pipeline with texture1 used as storage image and texture2 as sampled image:

```
BIND BUFFER texture1 AS texture DESCRIPTOR_SET 0 BINDING 0
BIND BUFFER texture2 AS texture DESCRIPTOR_SET 0 BINDING 1
BIND SAMPLER sampler DESCRIPTOR_SET 0 BINDING 2
```

But a case where texture1 was a sampled image and texture2 a storage image would have identical syntax.

Combined image samplers are easy as they will have the texture and sampler bound to the same set and binding.

**Comment by dj2** [comment]
K, let me see if I have things straight. Looking at the vulkan spec we have:

```
storage buffer (VK_DESCRIPTOR_TYPE_STORAGE_BUFFER)  // Done
uniform buffer (VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER)  // Done

Storage image (VK_DESCRIPTOR_TYPE_STORAGE_IMAGE)
Sampler (VK_DESCRIPTOR_TYPE_SAMPLER)
Sampled Image (VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE)
Combined Image (VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER)
uniform texel buffer (VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER)
storage texel buffer (VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER)

dynamic uniform buffer (VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC)
dynamic storage buffer (VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC)

input attachment (VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT)
```
this issue was looking at adding `texture` to the buffer command, which I think maps to `VK_DESCRIPTOR_TYPE_STORAGE_IMAGE`, correct? Maybe we want to be more explicit, and instead of saying `texture` we say `storage_image` then later we can add a `sampled_image` and the various other samplers? When we get there we can add a `uniform_texel` and `uniform_dynamic` to go with the current uniform?

Would that clear things up or make it more confusing?

**Comment by asuonpaa** [comment]
That's exactly what I meant in my previous comment. I'll proceed with this plan.
