### ISSUE TITLE
Vulkan: When requirements not met, failure message should name the missing extension

### ISSUE THREAD

**Issue by dneto0** [google/amber#336]
I can dig up an example.

**Comment by dj2** [comment]
We don't necessarily know which extension/requirement failed, but I'm updating the code to make it clear the failure is not finding extension/feature required.

**Comment by dj2** [comment]
I'm going to close this out as I think it's basically handled. We don't know the specific extension because you could have multiple devices and they all have different things, but it is pretty clear it's an extension issue when you get the error now.
