### ISSUE TITLE
Unnecessary namespace in macro definitions?

### ISSUE THREAD

**Issue by hevrard** [google/amber#349]
`platform.h` only operates on preprocessor macros, are namespaces any useful here?
https://github.com/google/amber/blob/596650447e65b80486cd5c83c278d1be46f348d5/src/platform.h#L19

In particular, these platform macros are not tied to Dawn I guess.

Should we remove the namespaces entirely? keep only the amber namespace?

**Comment by dj2** [comment]
Good catch, that file got moved from the dawn directory. I'd prefer to keep the amber namespace, for consistency and in case we add non-macro methods they'll already be there. The dawn namespace should have been removed when the file was moved but we forgot.

**Comment by hevrard** [comment]
OK, I can take care of this.
