### ISSUE TITLE
Dump image data

### ISSUE THREAD

**Issue by dj2** [google/amber#35]
There is an un-implemented command line option to the amber script to dump image data, this should be implemented.

**Comment by hevrard** [comment]
The framebuffer contents is already accessed by the verifier (to probe pixel values) via:
`engine->GetFrameBufferInfo(info); // info.cpu_memory is then a pointer to pixel values`

The verifier then assumes a R8G8B8A8 format, with TODO comments saying more formats should be supported:
https://github.com/google/amber/blob/4336157fe1e4293f4b7b5e5d201571c7b71eff08/src/verifier.cc#L243

So as a first step, we may add a method
`Engine::GetFrameBufferAsR8G8B8A8(std::vector<uint8_t> *pixels)`
(or with a better name) which let the engine take care of any format conversion needed, and fails if the framebuffer format cannot be translated to R8G8B8A8.

Then use this method both in `Verifier::Probe()` and as a basis to dump the image in a PPM file.

Does this sound good?

**Comment by dj2** [comment]
The CL to add all image formats is https://github.com/google/amber/pull/224 being worked on by @jaebaek . I'd prefer if the engine returned Value objects, just to make it clear what the format is, why not do Engine::GetFrameBuffer(std:;vector<Value>* pixels) and for now, just return r8g8b8a1 then we can just update it to do the right thing when the other CL lands.

Then, on the output side, just as the Value what type of data it contains. That way, the writing code should be good to go as soon as the engine returns the other formats.

**Comment by dj2** [comment]
Thinking about this a bit more, it might make sense to return this as a DataBuffer. That way you can have the vector of Values and the data buffer will describe the format the data is in.

**Comment by dj2** [comment]
Fixed by #227
