### ISSUE TITLE
PYTHON_EXECUTABLE should be used under Windows

### ISSUE THREAD

**Issue by archimedus** [google/amber#398]
Cannot build https://github.com/KhronosGroup/VK-GL-CTS after https://github.com/google/amber/pull/328

It looks like instead of PYTHON_EXE a variable PYTHON_EXECUTABLE should be used, though not checked the fix under linux.

Similar issue: https://github.com/google/shaderc/issues/152 , though I don't have PYTHON_EXE at all.

Could you please check?

**Comment by dj2** [comment]
If you don't have python, Amber will not build. I've put up #401 to make it required in the README.

**Comment by alegal-arm** [comment]
I think Boris meant that here (https://github.com/google/amber/blob/master/src/vulkan/CMakeLists.txt#L56) Amber should use PYTHON_EXECUTABLE instead of PYTHON_EXE

**Comment by dj2** [comment]
Oh, sorry I thought you were saying you didn't have python, not that you didn't have the environment export.

**Comment by dj2** [comment]
Fixed, thanks a lot for the bug report.
