### ISSUE TITLE
gcc 7.3: desc_type  maybe uninitialized in src/vulkan/pipeline.cc

### ISSUE THREAD

**Issue by alegal-arm** [google/amber#404]
gcc 7.3 complains

/usr/bin/g++  -DAMBER_CTS_VULKAN_HEADER=1 -DAMBER_ENABLE_SHADERC=0 -DAMBER_ENABLE_SPIRV_TOOLS=0 -DAMBER_ENGINE_DAWN=0 -DAMBER_ENGINE_VULKAN=1 -DDE_ASSERT_FAILURE_CALLBACK -DDE_COMPILER=DE_COMPILER_GCC -DDE_CPU=DE_CPU_X86_64 -DDE_OS=DE_OS_UNIX -DDE_PTR_SIZE=8 -I../../external/amber/../vulkancts/framework/vulkan -I../../framework/delibs/debase -I../../framework/delibs/decpp -I../../framework/delibs/depool -I../../framework/delibs/dethread -I../../framework/delibs/deutil -I../../framework/delibs/destream -I../../external/zlib/src -I../../external/vkrunner/src -I../../external/spirv-headers/src/include -I../../external/amber/src/include -I../../external/amber/src -I. -Wall -Wextra -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -Werror -Wno-error=unused-function -Wno-implicit-fallthrough -m64 -std=c++03 -Wno-delete-non-virtual-dtor -fwrapv -fvisibility=hidden -fvisibility-inlines-hidden -std=c++11 -fvisibility=hidden -Wall -Werror -Wextra -Wno-unknown-pragmas -Wpedantic -pedantic-errors -O3 -DNDEBUG -fPIC   -fno-exceptions -fno-rtti -std=gnu++11 -MD -MT external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o -MF external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o.d -o external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o -c ../../external/amber/src/src/vulkan/pipeline.cc

../../external/amber/src/src/vulkan/pipeline.cc: In member function 'amber::Result amber::vulkan::Pipeline::CreateDescriptorSetLayouts()':

../../external/amber/src/src/vulkan/pipeline.cc:117:38: error: 'desc_type' may be used uninitialized in this function [-Werror=maybe-uninitialized]

       bindings.back().descriptorType = desc_type;

       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~

**Comment by dj2** [comment]
Fixed by #402
