### ISSUE TITLE
clang-3.4 detected unreachable code

### ISSUE THREAD

**Issue by alegal-arm** [google/amber#405]
FAILED: /usr/bin/clang++   -DAMBER_CTS_VULKAN_HEADER=1 -DAMBER_ENABLE_SHADERC=0 -DAMBER_ENABLE_SPIRV_TOOLS=0 -DAMBER_ENGINE_DAWN=0 -DAMBER_ENGINE_VULKAN=1 -DDE_ASSERT_FAILURE_CALLBACK -DDE_COMPILER=DE_COMPILER_CLANG -DDE_CPU=DE_CPU_X86_64 -DDE_DEBUG -DDE_OS=DE_OS_UNIX -DDE_PTR_SIZE=8 -Wall -Wextra -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -Werror -Wno-error=unused-function -Wno-error=unused-command-line-argument -m64 -std=c++03 -Wno-delete-non-virtual-dtor -fwrapv -fvisibility=hidden -fvisibility-inlines-hidden -std=c++11 -fvisibility=hidden -Wall -Werror -Weverything -Wextra -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-format-pedantic -Wno-padded -Wno-switch-enum -Wno-unknown-pragmas -Wno-unknown-warning-option -g -fPIC -I../../external/amber/../vulkancts/framework/vulkan -I../../framework/delibs/debase -I../../framework/delibs/decpp -I../../framework/delibs/depool -I../../framework/delibs/dethread -I../../framework/delibs/deutil -I../../framework/delibs/destream -I../../external/zlib/src -I../../external/vkrunner/src -I../../external/spirv-headers/src/include -I../../external/amber/src/include -I../../external/amber/src -I.    -fno-exceptions -fno-rtti -Wno-zero-as-null-pointer-constant -MMD -MT external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o -MF "external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o.d" -o external/amber/src/src/vulkan/CMakeFiles/libamberenginevulkan.dir/pipeline.cc.o -c ../../external/amber/src/src/vulkan/pipeline.cc

../../external/amber/src/src/vulkan/pipeline.cc:44:17: error: will never be executed [-Werror,-Wunreachable-code]

  return Result("Unknown resource type");

                ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by dj2** [comment]
Sigh, the different ways compilers complain about unreachable and switch statements ....

**Comment by alegal-arm** [comment]
Try adding static analysis tools on top :)

**Comment by dj2** [comment]
#406 will fix this, but it may make MSVC sad, we'll see if it passes the bots, otherwise I'll make the code silly and have it work.
