### ISSUE TITLE
Clarify semantics of the Shutdown() commands

### ISSUE THREAD

**Issue by dj2** [google/amber#42]
Does it mean:
- I can never use this object again?  If so then I'd call it Destroy()
- Reset() . -- I can revive this object by re-initializing it?

---

It means never use again. For anything in Shutdown() that doesn't require error checking we can probably move it to the Destructor. Shutdown is there so we can error check the closing of our resources (similar to the Initialize() for startup).

**Comment by jaebaek** [comment]
I think we cannot move it to Destructor even though it doesn't require error checking.
Vulkan resource has its own order of destroying resources.
For example, device cannot be destroyed before all resources are destroyed.
Let me just change its name to `Destroy()`.

**Comment by dj2** [comment]
I don't get any validation errors on MoltenVk running it this way. Are you getting validation errors with this code?

**Comment by dj2** [comment]
All the Shutdown methods have been removed in favour of destructors.
