### ISSUE TITLE
Check stride row for VkImage

### ISSUE THREAD

**Issue by jaebaek** [google/amber#423]
As discussed [here](https://github.com/google/amber/pull/415/files/cc6bcea1432112d92a724063f9a7af31737551de#r269246378), currently Amber Vulkan backend uses the width of an image as a row stride.

It can be a bug and we must doublecheck if we need a separate value for a row stride.

**Comment by dj2** [comment]
Do you have a repro script? If not, there isn't much we can do here. Until we have a known issue I don't think we need a bug open.

**Comment by dj2** [comment]
Chatted with jaebaek@, closing until we have a repro case.
