### ISSUE TITLE
Add RUN support for OPENCL-C shaders

### ISSUE THREAD

**Issue by dj2** [google/amber#427]
The run command can currently either draw or execute compute kernels. What changes need to be done to support opencl-c?

```
SHADER opencl-c my_kernel CLSPV
kernel void foo(global int4* in, global int4* out, int z) {
  out[z] = in[z];
END
BUFFER in_buf TYPE int4 DATA
7 4 2 3
END
BUFFER out_buf TYPE int4 SIZE 1

PIPELINE my_pipeline
  ATTACH my_kernel
  BIND BUFFER foo OPENCL-C KERNEL in_buf ARG in
  BIND BUFFER foo OPENCL-C KERNEL out_buf ARG out
END
RUN my_pipeline  # Just this? Or something else?
```

**Comment by dj2** [comment]
@alan-baker Does RUN need to take extra params for clspv?

**Comment by alan-baker** [comment]
Number of workgroups

**Comment by alan-baker** [comment]
Number of workgroups is supported already. The only additional thing I can think might be appropriate here is changing the POD data args that were set via the SET KERNEL command.

**Comment by dj2** [comment]
I think we have the parts of this in place, I'm going to close and we can open additional issues if needed.
