### ISSUE TITLE
Add a SET command for OPENCL-C

### ISSUE THREAD

**Issue by dj2** [google/amber#428]
Along with binding buffers to kernels we need to be able to set scalar arguments:

```
SHADER opencl-c my_kernel CLSPV
kernel void foo(global int4* in, global int4* out, int z) {
  out[z] = in[z];
END
BUFFER in_buf TYPE int4 DATA
7 4 2 3
END
BUFFER out_buf TYPE int4 SIZE 1

PIPELINE my_pipeline
  ATTACH my_kernel
  BIND BUFFER foo OPENCL-C KERNEL in_buf ARG in
  BIND BUFFER foo OPENCL-C KERNEL out_buf ARG out
  SET OPENCL-C DATA KERNEL foo ARG z 2
END
RUN my_pipeline
```

This would set the z argument to 2 when the pipeline is executed. If there are multiple arguments they may need to get combined into a single POD argument based on what the clspv computer requests.

**Comment by dj2** [comment]
@alan-baker would you want to change the value of SET over run calls, or is it only set once?

**Comment by alan-baker** [comment]
If you could change the SSBOs between runs then yes, probably want to be able to change the POD args.

**Comment by alan-baker** [comment]
I mentioned the wrong issue. This still remains to be done.
