### ISSUE TITLE
Figure out compiler options for CLSPV

### ISSUE THREAD

**Issue by dj2** [google/amber#433]
For SPIRV we have a SHADER_OPTIMIZATION section in the PIPELINE. We should investigate something similar to pass options to CLSPV.

**Comment by alan-baker** [comment]
I think this definitely needs to be per-pipeline. I would propose something almost the same as the optimizations:
```
COMPILE_OPTIONS {shader}
  <option>+
END
```

This will allow generation of pipeline variants that set up the interface differently based on the command line options.

**Comment by dj2** [comment]
I like `COMPILE_OPTIONS`. We can reuse it for DXC and GLSLang if we get to the point where we need custom options for them. I've been trying to decide if they were the same as `SHADER_OPTIMIZATION` but I think they're separate. You may want to do both specify compiler options and `spirv-opt` passes of the resultant binary.
