### ISSUE TITLE
Vulkan: need to set render-pass load-op correctly

### ISSUE THREAD

**Issue by SteveHill-BRCM** [google/amber#436]
There is a TODO in https://github.com/google/amber/blob/master/src/vulkan/graphics_pipeline.cc line 33 related to setting the load and store ops for the render passes which seems to be causing some tile-based GPUs to fail some up-coming Amber-based deqp-vk tests (see https://gerrit.khronos.org/#/c/3712/).

If the render-pass object is being re-used, and the image data is expected to persist from one pass to the next, then the load-op should be set to "load".

**Comment by dj2** [comment]
If we always do load op load would that work? Do you have a test file we
can put in Amber to make sure we get this right?

Thanks,
Dan

**Comment by SteveHill-BRCM** [comment]
Hi Dan -- thanks for the response.  I think that load would be fine.  It may not be optimal - for example if you immediately clear, but I guess that is not really a concern for these tests.  I will get an example for you.

Thanks,
Steve.

**Comment by SteveHill-BRCM** [comment]
[line_list.amber.txt](https://github.com/google/amber/files/3022794/line_list.amber.txt)

Here is one of the tests in question.

Thanks,
Steve.

**Comment by dj2** [comment]
I don't have a tiling CPU so the test case passes either way for me. I've put up a CL which adds the test and flips to LOAD_OP_LOAD. Can you verify this fixes the issue you're seeing?

**Comment by SteveHill-BRCM** [comment]
Thank you.  Yes it works for me.  Without the change we fail, with it we pass.
