### ISSUE TITLE
what specifies width and height of color and depth-stencil attachments?

### ISSUE THREAD

**Issue by dneto0** [google/amber#468]
From a code review: https://github.com/google/amber/pull/467#discussion_r275067682

The Amber pipeline object has both a GetFramebufferWidth and GetFramebufferHeight.
But it also has color attachments that have a BufferInfo and hence Buffer object inside, and that Buffer has both GetWidth and GetHeight.

So... which is authoritative?

Should backend engines ignore the ::amber::Pipeline::GetFrambuffer{Width|Height} methods?  It seems that way to me.  It seems those are only there for the parser to set and for the ::amber::Pipeline to create its own BufferInfo objects from.  Then backends should only pay attention to the BufferInfo objects themselves.

**Comment by dj2** [comment]
You want the GetFramebufferWidth and Height methods. The bufferinfo width/height are a reply channel back to the host application if buffer extractions were requested.

**Comment by dj2** [comment]
I believe this is now resolved. Closing.
