### ISSUE TITLE
Redefined buffer types

### ISSUE THREAD

**Issue by jaebaek** [google/amber#48]
AmberScript's [buffer type](https://github.com/google/amber/blob/master/docs/amber_script.md#buffer-types) is confusing.

I feel that we should have the following buffer types:
- color for color attachment of framebuffer
- depth stencil for depth/stencil attachment of framebuffer
- vertex for vertex buffer
- index for index buffer
- storage image
- sampled image
- combined image sampler
- uniform texel buffer
- storage texel buffer
- storage buffer
- uniform buffer
- input attachment

Note that here we also uses the term 'buffer' for image because in the view of Amber script, the image is also a sequence of bytes.

Since storage image, sampled image, combined image sampler, uniform texel buffer, storage texel buffer, storage buffer, uniform buffer, and input attachment are [Vulkan specific descriptor types](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#descriptorsets-types) and I am not sure WebGPU will define the same types or not, we would better consider how to support buffers of WebGPU efficiently.

**Comment by jaebaek** [comment]
As we discussed in offline, an alternative is to separate the type from buffer and add the type argument for `DESCRIPTOR_SET` command. In that way, the buffer is just a data blob and we can also run WebGPU resource types with the same data.

**Comment by dj2** [comment]
This was done in #66
