### ISSUE TITLE
Support push constants in AmberScript

### ISSUE THREAD

**Issue by dj2** [google/amber#480]
Currently push constants can not be bound as they do not have a descriptor set or binding.

**Comment by dneto0** [comment]
Dawn does not support push constants, and won't support it.
I presume this will be caught and reported in the CreatePipeline engine call.

**Comment by dj2** [comment]
Yea, we'll need to add a flag into the pipeline that a push_constant buffer has been created otherwise the pipeline doesn't actually know. But,we can do that when we get there with the Dawn engine. I'll file a bug.
