### ISSUE TITLE
support 16bit float, a.k.a. half type

### ISSUE THREAD

**Issue by dneto0** [google/amber#485]
The tricky part of this is that C/C++ don't have native support for it.
There are various headers-only libraries for maniuplating them, including one in SPIRV-Tools that awoloszyn wrote

**Comment by dneto0** [comment]
oh wait, i saw some ...

**Comment by dj2** [comment]
We have code to read 10, 11 and 16 bit floats. I'm not sure if they'll parse correclty, but we do have conversion code already. Can you put up an example amber script which uses float16? Would make it easier to figure out what needs fixing.
