### ISSUE TITLE
Buffer data forced to use consistent types

### ISSUE THREAD

**Issue by dneto0** [google/amber#497]
The type declaration for each buffer must be consistent across all subdata.  This is a newly enforced rule.  It's not documented.

If ultimately all the scalars use the same basic type then we can fake it by using lowest-common denominator type.  For example, if we want to mix uint with uvec4, then use uint where instead of uvec4.  But we still can't mix float and integer data in a single buffer.

Example:
```
[compute shader]
#version 450

layout(set = 0, binding = 0, std140) uniform UBO {
        uint a[2];
        uvec4 b;
        uvec3 c;
        uvec2 d;
} Ubo;

layout(set = 0, binding = 1, std430) buffer BUF {
        uint a[2];
        uvec4 b;
        uvec3 c;
        uvec2 d;
} Buf;

void main() {
        Buf.a[0] = Ubo.a[0];
        Buf.a[1] = Ubo.a[1];
        Buf.b = Ubo.b;
        Buf.c = Ubo.c;
        Buf.d = Ubo.d;
}

[test]
# Array stride in UBO is a multiple of 16
uniform ubo 0:0 uint 0 1
uniform ubo 0:0 uint 16 2
# Really uvec4, but can fake it if we say "uint" here
uniform ubo 0:0 uvec4 32 3 4 5 6
# Really uvec3, but can fake it if we say "uint" here
uniform ubo 0:0 uvec3 48 7 8 9
# Really uvec2, but can fake it if we say "uint" here
uniform ubo 0:0 uvec2 64 10 11
ssbo 0:1 72

compute 1 1 1

probe ssbo uint 0:1 0 == 1
probe ssbo uint 0:1 4 == 2
probe ssbo uint 0:1 16 == 3 4 5 6
probe ssbo uint 0:1 32 == 7 8 9
probe ssbo uint 0:1 48 == 10 11
```

With this, Amber complains:
ubo_to_ssbo.vkscript: 31: probe ssbo format does not match buffer format

**Comment by dneto0** [comment]
At the very least the script language documentation should mention this limitation.

**Comment by dj2** [comment]
So, this change was done on purpose. I'll update the documentation to better explain that types must match now.

Having a buffer accept multiple data types can allow things like updating a vec4 in the middle (we had a test which did this, it overwrite the last 2 bytes of 1 vec4 and the first 2 bytes of the next). There is no way to know if what you're doing is correct, it also makes the tests a lot harder to understand.

**Comment by cmarcelo** [comment]
If a buffer accept only one data type, would make sense then to set it when the buffer is created?

I suspect that would've avoided the issue in #501.

**Comment by dj2** [comment]
AmberScript requires the buffer to be filled at one time. VkScript does not, but has the restriction the buffer must be consistent. The VkScript format was defined prior to Amber and we don't want to change it too much.
