### ISSUE TITLE
AmberScript: image dump requires buffer named "framebuffer"

### ISSUE THREAD

**Issue by hevrard** [google/amber#505]
```
PIPELINE graphics my_pipeline
  [...]
  # This buffer MUST be named "framebuffer" for the image dump to work
  BIND BUFFER framebuffer AS color LOCATION 0
END
```

Not sure if it is a bug or feature, but it should at least be clarified in the doc.

**Comment by dj2** [comment]
It's currently a limitation in the sample app. We should be able to specify the buffer name for image dump but it's currently hardcoded to the 'framebuffer' which vkscript uses.

**Comment by dj2** [comment]
Does #507 work sufficiently for you to fix this?

**Comment by hevrard** [comment]
That's good, many thanks!
