### ISSUE TITLE
Support scratch buffers: no subdata, no probe

### ISSUE THREAD

**Issue by dneto0** [google/amber#513]
Followup to #501 

Currently Amber blindly copies all buffers back and forth between CPU and GPU, and for that it requires a format.  To get a format, the script needs to include either a subdata or probe.
This requirement is confusing and pollutes user scripts.

We should support scratch buffers that have a size but no probe or subdata.

**Comment by dj2** [comment]
I think the right thing to do here is set a default format on the ssbo size command of <int>. That format will be replaced if a `subdata` or `probe` command is run.

This will allow us to still extract the buffer, even if the format isn't set, we're just going to assume it's a buffer of all ints.
