### ISSUE TITLE
File not closed yet

### ISSUE THREAD

**Issue by 360CodeSafe** [google/amber#532]
file open here
https://github.com/google/amber/blob/25852407411ad592a32f5732f68dbb70134277f4/samples/amber.cc#L202

a 'fclose(file);' should be add here:
https://github.com/google/amber/blob/25852407411ad592a32f5732f68dbb70134277f4/samples/amber.cc#L211-L214

Even if it is just a sample, close the file when the file pointer is not used as a better software engineering perspective.

**Comment by dj2** [comment]
Thanks for pointing that out, patch is out for review.
