### ISSUE TITLE
Ship vulkan layers with Amber

### ISSUE THREAD

**Issue by dj2** [google/amber#539]
There have been at least two instances where unknown layers have caused issues with Amber. We should ship the vulkan layers with Amber, build them, and then either add an execution script which will load them, or note in the readme the env settings to export to pickup our layers.

**Comment by dj2** [comment]
@s-perron @sarahM0 @jaebaek @dneto0

**Comment by dneto0** [comment]
I'm not so sure.  Are the layers more coupled to the driver or to the application?

**Comment by dj2** [comment]
The layers are application side, not driver side. There is nothing in the SDK which is driver specific (at least not that I know of).
