### ISSUE TITLE
Set glslang environment based on amber command line arguments

### ISSUE THREAD

**Issue by jeffbolznv** [google/amber#549]
GLSL shaders using subgroup operations require Vulkan 1.1/SPIR-V 1.3, but amber doesn't pass the Vulkan version through shaderc to glslang. So a shader that uses subgroup operations generates an error like "'subgroup op' : requires SPIR-V 1.3" even if the command line includes "-v 1.1".

The issue appears to be that ShaderCompiler::CompileGlsl doesn't set the target environment in its local options variable. Adding "options.SetTargetEnvironment(shaderc_target_env_vulkan, shaderc_env_version_vulkan_1_1);" as a hack fixes this. So we need code to translate the amber command line arguments to the appropriate shaderc options so glslang's client/version get set correctly.

**Comment by dneto0** [comment]
The source language, target language, client language environment, target environment  for Amber, Shaderc, Glslang, and SPIR-V tools aren't consistent.
I'm working out how to best address this in a sustainable way.

**Comment by dj2** [comment]
The Amber target environment uses the SPIRV-Tools parsing through the spvParseTargetEnv method.

**Comment by dneto0** [comment]
> The Amber target environment uses the SPIRV-Tools parsing through the spvParseTargetEnv method.

The HLSL flow passes the string to dxc, which then translates vulkan1.0 to -fspv-target-env=vulkan1.0 and vulkan1.1 to -fspv-target-env=vulkan1.1, and allows no other values.

One of the questions is whether to control compilation dialect via -v or via -t:
-   -v selects engine version to run against.  
-   -t selects "target spir-v environment" which, yeah, is from SPIRV-Tools concepts, but folds both runtime environment and spir-v version together (unfortunately, but hey we're too far along now.)

I'm leaning to controling compilation dialect only via -t rather than via -v.  So you can compile GLSL to vulkan1.0 and SPIR-V but then run against a Vulkan 1.1 driver.

**Comment by dneto0** [comment]
I've worked out the necessary changes, described below.
The weirdness is Amber environment string/enum is the same as SPIRV-Tools target env string and enum.  That comingles the concept of SPIR-V version with the client API that will be using/running the module.
But Shaderc and Glslang keep those concepts separate.

So the plan below accommodates that separation even though the invocation flow is:
  Amber -> Shaderc -> Glslang 
And it also has to accommodate SPIR-V assembly modules in a sane way.

I'm welcoming feedback from @alan-baker 
---------
Amber changes:
  Summary: add ability to override SPIR-V version generated by the compiler.
  Better document that the -t command line option is the same set of strings
  as used for SPIRV-Tools target environment.

  Examples:
        amber foo.amber
           - Assembly shaders use SPIR-V 1.0
           - GLSL shaders use Vulkan 1.0
           - HLSL errors out

        amber -t spv1.0 foo.amber // Same as above

        amber -t spv1.2 foo.amber
           - Assembly shaders use SPIR-V 1.2
           - GLSL shaders use Vulkan 1.1
           - HLSL errors out

        amber -t spv1.3  foo.amber
           - Assembly shaders use SPIR-V 1.4
           - GLSL shaders use Vulkan 1.1
           - HLSL errors out

        amber -t spv1.4  foo.amber
           - Assembly shaders use SPIR-V 1.4
           - error out for GLSL (or other high level shader compilation)
           - HLSL errors out

        amber -t vulkan1.0  foo.amber
           - Assembly shaders use SPIR-V 1.0
           - GLSL shaders use Vulkan 1.0
           - HLSL uses vulkan1.0

        amber -t vulkan1.1  foo.amber
           - Assembly shaders use SPIR-V 1.3
           - GLSL shaders use Vulkan 1.1
           - HLSL uses vulkan1.1

        amber -t vulkan1.1spv1.4  foo.amber
           - Assembly shaders use SPIR-V 1.4
           - GLSL shaders use Vulkan 1.1
           - HLSL errors out: FUTURE make this better?

-  amber tool -t <environment>

   Document that only the last setting counts.

   String options are same as SPIRV-Tools environment string, e.g.
        spv1.0
        vulkan1.1
        vulkan1.1spv1.4

   (amber executable doesn't link to SPIRV-Tools, so we don't validate this
   until we try to execute the recipe)

   Document that default is SPIR-V 1.0 generation, and Vulkan 1.0 client API
   for high level compilation and validation.

   Sets this string into the amber::Options::spv_env member.

- Amber ShaderCompiler:

  - Mapping spv_env string to client API version and generate-for-SPIR-V version:

       If spv_env is unset, default as if it's vulkan1.0

       If spv_env options is Vulkan-specific:
         - client API environment uses the specified Vulkan version
         - generate-for-SPIR-V version:
           if spv_env is vulkan1.1spv1.4, then map to SPIR-V 1.4
           otherwise use the highest version required to be supported
           by the client API environment.

       If spv_env option is a SPIR-V only environment.
         - client API environment defaults to lowest Vulkan requiring
           support for that version of SPIR-V. (e.g. Vulkan1.1 if spv1.3)
           If there is no such Vulkan, then error out.
         - generate-for-SPIR-V version will use that specific SPIR-V version

       If spv_env options is WebGPU-specific: FUTURE

  - SPIR-V validation: uses client API environment determined above.

  - SPIR-V Assembly or SPIRV-HEX path:
      use generate-for-SPIR-V version determined above.

  - GLSL compilation path:
      Already requires Shaderc, which means SPIRV-Tools must be available.

      Use Shaderc SetTargetEnv with client API version determined above.
      Use Shaderc SetSpirvVersion with generate-for-SPIR-V version determined above.

Shaderc changes:
  Summary: add ability to override SPIR-V version generated by the compiler.
  Avoid mixing enums for client API with SPIR-V version override. (Match Glslang)

- add enum shaderc_spirv_version {
   shaderc_spirv_version_1_0
   shaderc_spirv_version_1_1
   shaderc_spirv_version_1_2
   shaderc_spirv_version_1_3
   shaderc_spirv_version_1_4

- add shaderc_compile_options_set_spirv_version
    sets the SPIR-V version of the generated module.
    overrides default compilation, which is highest spir-v version in core of target env:
                vulkan1.0 -> spir-v 1.0
                vulkan1.1 -> spir-v 1.3
                OpenGL* -> spir-v 1.0

  - document interaction with shaderc_get_spv_version
    That doesn't know the shaderc_compile_options object, so it can't answer
    correctly.  So update the description to say it's the max version known
    by Shaderc.  It's the spv::Version and spv::Revision reported by the
    SPIRV-Headers we compiled with.

- libshaderc_util::Compiler
   -  add enum SpirvVersion {
        // corresponding to shaderc_spirv_version
        SPIRV_1_0, SPIRV_1_1, .... }

   - add method SetSpirvVersion
        // Sets the forced version of SPIR-V on the generated module.
        // Default is the highest version of SPIR-V required
        // to be supported by the target environment.
        // e.g. Vulkan 1.0 -> SPIR-V 1.0
        // e.g. Vulkan 1.1 -> SPIR-V 1.3
        // (Recall target environment defaults to Vulkan 1.0)

   - Compiler methods:
        - already call Glslang's setEnvClient to set client API version
        - if SetSpirvVersion has been called, then use those values in the
          Glslang setEnvTarget.

**Comment by dj2** [comment]
Why does HLSL error out in so many cases?  Does HLSL not support vulkan1.0 or spv 1.0? If so, can we just auto set spv1.1 and vulkan1.1 if HLSL shaders are detected?

Having it just fail if you run `amber foo.hlsl` is a bad user experience if we know how to run the script correctly.

Can GLSL not generate spv1.4?

**Comment by dneto0** [comment]
> Why does HLSL error out in so many cases? Does HLSL not support vulkan1.0 or spv 1.0? If so, can we just auto set spv1.1 and vulkan1.1 if HLSL shaders are detected?

My mistake, plain "amber foo.amber" with HLSL should assume Vulkan 1.0, just like GLSL.

> Can GLSL not generate spv1.4?

Yes it can.   

I'm suffering from the Monday-morning-what-was-I-thinking blues.  The table has another typo, and doesn't even follow the rule "if spv_env option is a SPIR-V only environment,
         client API environment defaults to lowest Vulkan requiring
           support for that version of SPIR-V. (e.g. Vulkan1.1 if spv1.3)
           If there is no such Vulkan, then error out."

Here's the table again, but hopefully fixed and more useful:

        amber foo.amber
           - Assembly shaders use SPIR-V 1.0
           - GLSL shaders use Vulkan 1.0, SPIR-V 1.0
           - HLSL shaders use Vulkan 1.0, SPIR-V 1.0

        amber -t spv1.0 foo.amber // Same as above

        amber -t spv1.1 foo.amber
           - Assembly shaders use SPIR-V 1.1
           - GLSL shaders use Vulkan 1.1, SPIR-V 1.1
           - HLSL errors out (DXC for Vulkan 1.1 only targets SPIR-V 1.3)

        amber -t spv1.2 foo.amber
           - Assembly shaders use SPIR-V 1.2
           - GLSL shaders use Vulkan 1.1, SPIR-V 1.2
           - HLSL errors out (DXC for Vulkan 1.1 only targets SPIR-V 1.3)

        amber -t spv1.3  foo.amber
           - Assembly shaders use SPIR-V 1.3
           - GLSL shaders use Vulkan 1.1
           - HLSL shaders use Vulkan 1.1

        amber -t spv1.4  foo.amber
           - Assembly shaders use SPIR-V 1.4
           - error out for GLSL, HLSL (until some Vulkan version requires support for SPIR-V 1.4)

        amber -t vulkan1.0  foo.amber
           - Assembly shaders use SPIR-V 1.0
           - GLSL shaders use Vulkan 1.0
           - HLSL shaders use Vulkan 1.0

        amber -t vulkan1.1  foo.amber
           - Assembly shaders use SPIR-V 1.3
           - GLSL shaders use Vulkan 1.1, SPIR-V 1.3
           - HLSL shaders use Vulkan 1.1, SPIR-V 1.3

        amber -t vulkan1.1spv1.4  foo.amber
           - Assembly shaders use SPIR-V 1.4
           - GLSL shaders use Vulkan 1.1, SPIR-V 1.4
           - HLSL errors out (unless DXC explicitly gets support for this)

**Comment by dj2** [comment]
Scanning the vulkan 1.1 doc, I don't see anything that precludes me from passing a spirv 1.4 module to a vulkan 1.1 application? You just can't use any stuff that isn't listed in the vulkan spec, yea?

**Comment by dneto0** [comment]
> Scanning the vulkan 1.1 doc, I don't see anything that precludes me from passing a spirv 1.4 module to a vulkan 1.1 application? You just can't use any stuff that isn't listed in the vulkan spec, yea?

Khronos specs describe what must work, and hence what can be tested in CTS.    They generally don't prohibit extra behaviour, e.g. as introduced by extensions.  So you don't see a prohibition of Vulkan 1.1 accepting SPIR-V 1.4.

That said, I think you're getting at asking why "amber -t spv1.4" should error out for GLSL or HLSL compilation.  We've got two choices here:

1. Error out. 

or:

2.  Have it compile the shader as if you had supplied vulkan1.1spv1.4.   But let's say a future version of Vulkan requires support for SPIR-V 1.4.   Does Amber now follow its other rule and for "-t spv1.4" target the lowest Vulkan that requires support for SPIR-V 1.4. Then that changes the meaning of a "working"  Amber script based on an external factor, which seems risky/wrong to me.  

I'd rather error out now in the meantime.  If the user really wants vulkan1.1spv1.4 then the user should say so.

**Comment by dj2** [comment]
3. Have it compile the shader as vulkan 1.1 spv1.4 and issue a warning "Vulkan 1.1 selected, this may change when a new vulkan version is released. Please specify -t vulkan1.1 if that is the desired environment'

That way, it runs and they still see something is wonky and we can change it later under them?

**Comment by dj2** [comment]
Mostly, it bugs me when software errors out and says "You typed quit, did you mean quit()". Just run what you think I wanted and tell me what I did wrong.

**Comment by dneto0** [comment]
> That way, it runs and they still see something is wonky and we can change it later under them?

Ok.  This is a least-surprise vs. usability argument.  I can see preserving the least-surprise-but-errors-more behaviour in the API level, but make the command line tool more usable, making it do-what-i-mean-and-warn-if-i'm-imperfect.
So in that case the above table would be the API behaviour, but I can make the command line tool be a lot more forgiving, with warning.

**Comment by dj2** [comment]
sgtm

**Comment by dneto0** [comment]
I've posted the Shaderc part: https://github.com/google/shaderc/pull/750
