### ISSUE TITLE
Validator might falsely fail requiring fragment shader

### ISSUE THREAD

**Issue by archimedus** [google/amber#553]
Enforcement of validation introduced in https://github.com/google/amber/pull/502 breaks certain tests with message

> graphics pipeline requires a vertex shader

This validation is not always correct, due to **Vulkan permits graphics pipelines without fragment shader** (please see 1.1.106, Valid Usage section of `VkGraphicsPipelineCreateInfo`):

> The stage member of one element of pStages must be either VK_SHADER_STAGE_VERTEX_BIT or VK_SHADER_STAGE_MESH_BIT_NV.

Method `vkscript::Parser::SkipValidationForTest()` cannot be used to alleviate the issue due to it is inaccessible from outside i.e. from class `amber::Amber`.

Please consider:
 * remove the validation check
 * make some alternative to `SkipValidationForTest()` available outside to give control over validation (for example extend `Amber::Parse()` with `bool validation=true` parameter)

As more long term solution it might be useful to create some amber file directives to control compilation/validation. If you find this idea useful please create separate issue, as I want this to be fixed quickly.

Thanks.

**Comment by dj2** [comment]
Is the fix for this just to not require a fragment shader in the validation? Does the card provide a default shader? If I have a pass through vertex shader and no fragment shader what happens?

**Comment by archimedus** [comment]
Output into SSBO is done. Example is here:

https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/data/vulkan/amber/pipeline/vertex_only/position_to_ssbo.amber

**Comment by dj2** [comment]
Ah, cool. So, it sounds like we just have to validate that the vertex shader is set and remove the check for the fragment shader?

Thanks a lot for pointing out the example. If you make the PR to fix the issue can you add the test to the tests/cases folder so we don't break it in the future?

**Comment by archimedus** [comment]
> Ah, cool. So, it sounds like we just have to validate that the vertex shader is set and remove the check for the fragment shader?

Fragment shader is not obligatory for graphics pipeline.

> Thanks a lot for pointing out the example. If you make the PR to fix the issue can you add the test to the tests/cases folder so we don't break it in the future?

 I supposed it would be better to exclude one test from the validation, but as far as I understand it's not an option. I abandoned my fix and pending for your fix. I suppose you will provide it faster. Thanks.
