### ISSUE TITLE
issue error if draw-rect requested for pipeline having vertex-data or index-data

### ISSUE THREAD

**Issue by dneto0** [google/amber#560]
That just doesn't make sense, because DRAW_RECT will supply its own vertices.

The parser should issue an error if the bad combination is found.

Affects both amber-script and vkscript flows

**Comment by sarahM0** [comment]
What if we use the same pipeline for a drawRect and a drawArray command?
For example in amber/tests/cases/draw_array_after_rect.vkscript a vertex data is attached for drawArray commands however drawRect uses it's own vertices.
I think drawRect needs to ignore the attach vertex/index data and uses what is supplied.

**Comment by dj2** [comment]
I'd be inclined to agree with @sarahM0. There is no reason you can't do both, we just have to make sure the drawRect gets its correct coordinates.

**Comment by dneto0** [comment]
Ok.   Then I think it would be reasonable for the AmberScript docs to say that with DRAW_RECT, if the pipeline has VERTEX_DATA or INDEX_DATA, then they are ignored.
I'll file a different issue for that.
