### ISSUE TITLE
AmberScript: Support instanced drawing in DRAW_ARRAYS

### ISSUE THREAD

**Issue by dneto0** [google/amber#565]
vkscript format supports instanced drawing:   At least, https://github.com/google/amber/blob/master/docs/vk_script.md has the syntax for instanced draw_arrays, but does not describe what it does.

**Comment by dj2** [comment]
This was one of those things where I need to see an example of how it's used/ what it does before being able to create a nice script language for it.

Once we have examples of instanced it can be revisited for addition to AmberScript.

**Comment by asuonpaa** [comment]
I have this task next on my list. Here's an example of an AmberScript syntax:

`RUN pipeline DRAW_ARRAY AS TRIANGLE_STRIP START_IDX 0 COUNT 4 START_INSTANCE 0 INSTANCE_COUNT 10`

START_INSTANCE and INSTANCE_COUNT would directly map to Vulkan vkCmdDraw instanceCount and firstInstance parameters.
