### ISSUE TITLE
Error out when DrawRect command is invoked on a pipeline with multiple vertex buffers attached

### ISSUE THREAD

**Issue by sarahM0** [google/amber#568]
The reason is we don't know where to bind the new vertex/index buffer which are going to be created according to the drawRect command. We could say e.g. location 1 is always reserved for drawRect command. However that imposes limitation on the shader code and it's generally too much since we can alway replace a drawRect command with a drawArray.
- We can issue the error in the executor (no need for change in the backends even if we add a new one)

**Comment by dj2** [comment]
Can't we determine this when we execute the drawRect? We should have all the buffers created with a location set, can we just loop over them and find max location? Only error out if we run out of locations?

**Comment by sarahM0** [comment]
That's a possibility, however we also need to add something like "layout(location = max) in vec4 draw_rect;" to the top of vertex shader module. Which is different form what is written in the script and the user wants to test.

**Comment by dj2** [comment]
Why do you need that? The current tests that use drawRect don't change the shader module.

**Comment by sarahM0** [comment]
The test that we have with drawRect do not use more than one input vertex buffers in their vertex shader  and that one is for the position (e.g. draw_array_after_draw_rect.vkscript has one input vertex buffer). For example a test like this that has two vertex input is not supported in Vulkan backend:
And one more issue could arise when vertex shader does anything more than passing through with position (e.g.   gl_Position = position + vec4(1.0, 1.0, 1.0, 1.0)). what do we do in that case?

SHADER vertex vtex_shader GLSL
#version 430

layout(location = 0) in vec3 position;
layout(location = 1) in vec4 ver_color;
layout(location = 0) out vec4 frag_color;


void main() {
  gl_Position = vec4(position, 1.0);
  frag_color = ver_color;
}
END

SHADER fragment frag_shader GLSL
#version 430

layout(location = 0) in vec4 frag_color;
layout(location = 0) out vec4 final_color;

void main() {
  final_color = frag_color;
}
END

BUFFER position_buf DATA_TYPE vec3<float> DATA
-1  1 0
-1 -1 0
 1  1 0
 1 -1 0
-1 -1 0
 1  1 0
END

BUFFER vert_color_buf DATA_TYPE R8G8B8A8_UNORM DATA
255   0   0 255
255   0   0 255
255   0   0 255
255   0   0 255
255   0   0 255
255   0   0 255
END

BUFFER framebuffer FORMAT B8G8R8A8_UNORM

PIPELINE graphics pipeline
  ATTACH vtex_shader
  ATTACH frag_shader

  VERTEX_DATA position_buf LOCATION 0
  VERTEX_DATA vert_color_buf LOCATION 1

  FRAMEBUFFER_SIZE 250 250
  BIND BUFFER framebuffer AS color LOCATION 0

END

RUN pipeline DRAW_RECT POS 100 100 SIZE 100 100
EXPECT framebuffer IDX 100 100 SIZE 100 100 EQ_RGBA 255 0 0 255

[ERROR] validation layer (Validation):
 [ UNASSIGNED-CoreValidation-Shader-InputNotProduced ] Object: 0x3 (Type = 15) | Vertex shader consumes input at location 1 but not provided

**Comment by dj2** [comment]
Ah, I see, bummer. You're right then, error out is about all we can do as the pipeline isn't usable. Do we have any VkScript's which doe something similar? Or did we just happen to add the test for AmberScript?

**Comment by sarahM0** [comment]
We don't have any test we more than one vertex shader that draws a rectangle. I'll add one when I close this issue. Or do mean something else?

**Comment by dj2** [comment]
Nope, didn't mean anything else. I think the answer for VkScript is that it just isn't possible to write this type of test as there is only one pipeline so it won't attach the shader correctly, yea? You'd end up with the same error as we have in AmberScript?

**Comment by sarahM0** [comment]
Yes and yes.

**Comment by sarahM0** [comment]
I added a fix which errors out in the parsing stage (in the executor I didn't see how to get access to the vertex buffers and anyways it's faster if we error out in parsing stage). Let me know what you think.
