### ISSUE TITLE
Resizing ssbo buffers to the same value increases their size

### ISSUE THREAD

**Issue by sarahM0** [google/amber#575]
This issue came out of MR #564 - for more info read the comments on it.
This issue is causing three tests to fail in dawn backend (theses have multiple ssbo calls for the same buffer as a result that buffer's size gets multiplied till it gets so big it overflows and dawn backed asserts for creating a buffer of size 0):
./cases/draw_array_after_draw_rect.vkscript
./cases/draw_rect_after_draw_array.vkscript
./cases/draw_rect_and_draw_array_mixed.vkscript

**Comment by sarahM0** [comment]
This issue came out of MR #564 - for more info read the comments on it.
This issue is causing three tests to fail in dawn backend (theses have multiple ssbo calls for the same buffer as a result that buffer's size gets multiplied till it gets so big it overflows and dawn backed asserts for creating a buffer of size 0):
./cases/draw_array_after_draw_rect.vkscript
./cases/draw_rect_after_draw_array.vkscript
./cases/draw_rect_and_draw_array_mixed.vkscript

**Comment by dj2** [comment]
Is this fixed, or just effected by the compute cl? @sarahM0

**Comment by sarahM0** [comment]
Well since we took another approach - using a separate member variable in buffer.cc to save the max size instead of changing the actual size while processing ssbo/ubo - this is not an issue anymore.
