### ISSUE TITLE
AmberScript: Fuzzy buffer comparisions

### ISSUE THREAD

**Issue by dj2** [google/amber#600]
There are times when we know the results written into a buffer may be slightly different (framebuffers where there can be slight colour differences due to floating point instability).

We need to a way to do fuzzy comparisons against buffers in AmberScript. Aside from the syntax in AmberScript we need to determine how fuzzy comparison will work. Do image comparisons work the same as non-image comparisons? I can see a few different ways  (maybe we need to implement all of them?)

  1. Absolute value comparison. Given a set of values (I'd guess the format must match the buffer format so a vec3 requires 3 values, a float 1) the absolute value of the difference at each point must be less or equal to the given value.
  1. Percentage value comparison. As above but each value given is a % difference
  1. Total difference less then x. Sum all values for each buffer, absolute difference must be less then the given value.
  1. Fancy image comparison thingy using fancy image stuff ....
  1. Something else?

For the syntax, this could be an extension along the lines of `BUFFER_EQ`. Something like `BUFFER_FUZZY_EQ` if there is only one option picked or more specific things like `BUFFER_ABS_VALUE_COMPARE` or something.

**Comment by dj2** [comment]
@dneto0 @afd @dnovillo

**Comment by dj2** [comment]
Something more complicated like Root Mean Square Error? (https://www.statisticshowto.datasciencecentral.com/rmse/)

**Comment by dnovillo** [comment]
RMSE has been giving decent results in our image comparison tests. Using a
threshold of .02 seems like a good compromise for us.

**Comment by dj2** [comment]
The RMSE patch has landed. Going to close this. If we want other kinds of fuzzy comparisons we can open new bugs.
