### ISSUE TITLE
AmberScript: Support images in tests

### ISSUE THREAD

**Issue by dj2** [google/amber#601]
We need to determine how to handle images in AmberScript. Are these an externally loaded resource? (Will have to plumb the loading through to the embedding environment through the `amber::Delegate`). Do we expect image to be hex encoded inside a buffer?

What special information do we need in `vulkan` and `dawn` to use those images?

**Comment by dj2** [comment]
@dneto0 @afd 

@sarahM0 for any insight into what Dawn might require in this respect.

**Comment by asuonpaa** [comment]
I could help with this task. See my comments on https://github.com/google/amber/issues/327.

**Comment by dj2** [comment]
We can load images local to files now, and declare various types of samplers in the amberscript files. I'm closing this as done, we can open follow up issues for extensions in the future.
