### ISSUE TITLE
Building with clspv enabled

### ISSUE THREAD

**Issue by ajitesh1509** [google/amber#621]
When trying to build amber with cmake -DAMBER_USE_CLSPV=TRUE -GNinja ../..
I get the following error after running the ninja command (screenshot of full error message attached.)
```
../../third_party/clspv-llvm/lib/Support/Unix/Process.inc:78:2: error: Cannot get the page size on this machine
#error Cannot get the page size on this machine
 ^
../../third_party/clspv-llvm/lib/Support/Unix/Process.inc:80:7: error: use of undeclared identifier 'page_size'
  if (page_size == -1)
      ^
../../third_party/clspv-llvm/lib/Support/Unix/Process.inc:83:32: error: use of undeclared identifier 'page_size'
  return static_cast<unsigned>(page_size);
<img width="1045" alt="Screen Shot 2019-08-22 at 12 43 46 PM" src="https://user-images.githubusercontent.com/54414080/63537073-86809880-c4da-11e9-956a-85b5fd112459.png">
```
I don't get the problem when I try to build without clspv. Any ideas how to fix this?

**Comment by alan-baker** [comment]
When I build on my macbook I have to change the setting for LLVM_BUILD_STATIC to OFF in third_party/CMakeLists.txt, but I always thought that was a configuration issue with my laptop. You could try that.

**Comment by ajitesh1509** [comment]
<img width="1040" alt="Screen Shot 2019-08-22 at 1 26 13 PM" src="https://user-images.githubusercontent.com/54414080/63539797-81264c80-c4e0-11e9-9436-c527809e6a2c.png">
I tried what you said I now have a different error

**Comment by alan-baker** [comment]
What versions are you using for cmake and your c compiler?

**Comment by alan-baker** [comment]
Try compiling:
```
#include <iostream>
int main() {
  std::cout << "Hello, world!\n";
  return 0;
}
```
With the c++ compiler cmake is using and add the following option:
```
-Wl,--color-diagnostics
```

That is the test that LLVM uses to determine if that flag is supported. It fails on my MacBook so that option is not added to my compiles. If you haven't I would wipe out the build directory and start fresh.

**Comment by ajitesh1509** [comment]
Thanks for the help Alan. I have tried starting fresh multiple times and I always get the same linker error when trying to build with clspv support and LLVM_BUILD_STATIC set to OFF.
Below is output of the test you asked me to do.
<img width="1046" alt="Screen Shot 2019-08-23 at 10 04 40 AM" src="https://user-images.githubusercontent.com/54414080/63602730-bccb2000-c58d-11e9-9ba4-5b3050649639.png">

**Comment by alan-baker** [comment]
I would double check which linker cmake is picking up, because based on that error LLVM shouldn't be attempting to add that flag. You could potentially just comment out that section around line 768 of third_party/clspv-llvm/cmake/modules/HandleLLVMOptions.cmake to hack around this particular problem.

**Comment by ajitesh1509** [comment]
Thank you so much, that worked and tests are working!
