### ISSUE TITLE
Android plain binary NDK build fails

### ISSUE THREAD

**Issue by paulthomson** [google/amber#648]
```
$ ${ANDROID_NDK_HOME}/ndk-build -C ../../samples NDK_PROJECT_PATH=. NDK_LIBS_OUT=`pwd`/libs NDK_APP_OUT=`pwd`/app
make: Entering directory `/gpu/amber/samples'
[arm64-v8a] Compile++      : SPIRV-Tools-opt <= amd_ext_to_khr.cpp
../third_party/spirv-tools/source/opt/amd_ext_to_khr.cpp:22:10: fatal error: 
      'spv-amd-shader-ballot.insts.inc' file not found
#include "spv-amd-shader-ballot.insts.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/gpu/amber/out/ndk/app/local/arm64-v8a/objs/SPIRV-Tools-opt/source/opt/amd_ext_to_khr.o] Error 1
make: Leaving directory `/gpu/amber/samples'
```

**Comment by dj2** [comment]
Are the third_party files all up to date? The NDK bot is still passing, so is it not working correctly?

**Comment by paulthomson** [comment]
I just tried again. I pulled and updated deps. Same error. We don't have a bot for building the [plain Android binary](https://github.com/google/amber#android-plain-executable).

**Comment by dj2** [comment]
@dneto0 is this github.com/KhronosGroup/SPIRV-Tools/issues/2883 ?

**Comment by paulthomson** [comment]
@asuonpaa Can you take a look at this if you get a chance? It might be that manually updating to the latest spirv-tools version will solve this. If so, perhaps you can "roll some deps" (as seen in a previous commit to master).

**Comment by asuonpaa** [comment]
Sure, I got the error reproduced. Let's see if just switching to the latest spirv-tools doesn't break anything else.
