### ISSUE TITLE
Windows build broken with newer Vulkan-Loader

### ISSUE THREAD

**Issue by dj2** [google/amber#649]
The Vulkan-Loaded added a dependency on the WDK in (https://github.com/KhronosGroup/Vulkan-Loader/pull/196). The readme specifies a WDK version o 1803 or later. Our bots all have versions which are earlier the that so we are unable to roll the loader code.

#645 has been attempting to roll the loader code. We have switched from Windows 7 to Windows Server 2016 bots in the Windows pool.

**Comment by dj2** [comment]
@dneto0 fyi

**Comment by dj2** [comment]
The Windows Server 2016 bots end up with `-- Found WDK: C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0` which seems to be to old as well.

**Comment by paulthomson** [comment]
Sounds like `-DCMAKE_SYSTEM_VERSION=10.0.17134.12` allows you to explicitly set it, but I guess it still needs to be present!

**Comment by dj2** [comment]
Yea, I don't think that version of the WDK is on the bots ....
