### ISSUE TITLE
vkWaitForFences timeout for slow implementations

### ISSUE THREAD

**Issue by jrprice** [google/amber#69]
The `CommandBuffer::SubmitAndReset` method uses a hardcoded timeout of 100 ms for the `vkWaitForFences` call. I'm sure this works great for all real Vulkan implementations, but for poor old emulators like Talvos this causes problems. For the `draw_triangles` test case I can scrape through if I bump the timeout to 200 ms (or switch to a Release build), but I'm guessing it might start failing again for larger test cases (or slower CPUs).

Assuming that you don't want to raise this hardcoded limit to O(seconds) just to accommodate Talvos' inefficiencies, would you perhaps accept a PR to enable the limit to be dynamically increased via an environment variable or command-line flag?

P.S. This looks to be an incredibly useful project, thanks for making it available!

**Comment by dj2** [comment]
Do you think adding this to the test script itself would be useful? If so, we could add to the `[require]` section in VkScript (and some undefined section I haven't spec'd yet for AmberScript) something like `fence_timeout <number>` which you can specify.

Or, are you looking to take general Amber scripts and run them on top of Talvos in which case modifying the script isn't really possible?

@dneto0

**Comment by jrprice** [comment]
My use cases today just involve using Amber as tool to test Talvos, so being able to put a `fence_timeout` or similar inside the scripts would work just fine for me.

I don't have any need to take try and run general Amber scripts on Talvos right now. That said, @dneto0 has previously expressed a possible desire to use Talvos as a software verification flow for related projects (I guess it might even be useful for CI testing Amber itself?!).

**Comment by dj2** [comment]
I think, in theory, we could have a Talvos engine for Amber, similar to the Vulkan and Dawn engines. Make it optional, then have it link in Talvos if available kinda thing. (Assuming Talvos provides a library we could link against?)

But, for this bug, I think the solution is to add the fence_timeout option to the require section of VkScript and have the vulkan engine use that if provided.

**Comment by jrprice** [comment]
> Assuming Talvos provides a library we could link against?

It does. However, since Talvos is just a Vulkan implementation, having a whole separate engine for it in Amber might be overkill? For example, Amber works fine on Talvos today using the Vulkan engine (with the scripts in `tests/cases` at least), and all I needed to do was pass `-DVulkan_LIBRARIES=talvos-vulkan` to the CMake invocation (assuming Talvos libraries on the search path). I think you could probably also just link Amber against a regular Vulkan SDK and then `LD_PRELOAD` Talvos.

**Comment by dj2** [comment]
I've put up #77 which adds the fence_timeout option into VkScript. The value is in milliseconds, please let me know if this does what you expect.
