### ISSUE TITLE
Clear Color default

### ISSUE THREAD

**Issue by sfricke-samsung** [google/amber#701]
Is the clear color defaulted to `[0,0,0,0]`? If so is this at an Amber level, Engine level, AmberScript level, etc? It would be nice if that was defined instead of having to stumble across `clear.amber`

**Comment by dj2** [comment]
The default clear colour, for vulkan, is defined in the https://github.com/google/amber/blob/master/src/vulkan/graphics_pipeline.h as (0, 0, 0, 0).  Are you saying you'd like to see that listed in the documentation? It is defined in the vkscript documentation, so we should define it in the amberscript documentation.

**Comment by sfricke-samsung** [comment]
I have only looked at amberscript... is it also defined as 0,0,0,0 in dawn? I would imagine this would be defined at an engine level.

Also I think a small declaration in amberscript would be good as well

**Comment by sfricke-samsung** [comment]
I don't feel this issue is worth any more change, but mainly curious now, with multiple input scripts and multiple engines how is something like the default color of the `amber::Pipleine` suppose to be ensured between everything to be consistent?

**Comment by dj2** [comment]
I'm not sure what you mean? You can only execute one engine at a time, and you can also only run one script at a time. If you're worried about the colour, you can always set the clear colour yourself in your script and call clear where needed.

Or, are you concerned someone will change the default value in the dawn engine to be something like (1, 0, 0, 0) so it isn't consistent anymore? In that case, it's dependant on code review and tests.

**Comment by sfricke-samsung** [comment]
Ok, I realize there are unit tests that would catch things... works for me, again just me trying to understand the agreement between everything.

Thanks
