### ISSUE TITLE
OpenCL assertion failure

### ISSUE THREAD

**Issue by tyler-utah** [google/amber#796]
Hi,

We were trying to write some OpenCL tests using clspv, but we get an assertion error when launching amber. 

First we synced clspv:

`git-sync-deps --with-clspv`

Then we build with clspv:

`cmake -GNinja -DAMBER_USE_LOCAL_VULKAN=1  -DAMBER_USE_CLSPV=TRUE ../..`

And after building, when we run amber, even with no input (e.g. `amber -d `), we get an error:

```
amber: ../../third_party/clspv-llvm/llvm/include/llvm/Support/CommandLine.h:853: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::ScheduleDAGInstrs* (llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* (llvm::MachineSchedContext*)]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.
```

Thanks in advance!

**Comment by dj2** [comment]
@alan-baker can you take a look? Looks like something when setting LLVM for CLSPV?

**Comment by alan-baker** [comment]
@tyler-utah if you build clspv on its own, do you also get this error trying to use the binary?

As can you share your system configuration? I've tested mac and linux release and debug builds and cannot reproduce this problem yet.

**Comment by tyler-utah** [comment]
Will do. The machine giving that error crashed shortly after, so I'm waiting for the admins to reboot it. In the meanwhile, I'm getting set up on a new machine. 

I'll let you know if the new machine has an issue, or if the issue remains on the old machine once its rebooted. Thanks!

**Comment by tyler-utah** [comment]
I'm going to close this issue because we lost access to this machine with COVID related restrictions. At some point, we'll get it back and I'll update things and try again. Thanks!
