### ISSUE TITLE
cleanup: draw_rect accepts vertex buffer, doesn't use it

### ISSUE THREAD

**Issue by jarikomppa** [google/amber#801]
The draw_rect command accepts one vertex buffer, but doesn't use it. Completely cleaning this up would require some changes to the VkScript as well, which may not be desirable.

**Comment by dj2** [comment]
I'm not sure I understand what this issue is about? What vertex buffer is `draw_rect` accepting? It creates a vertex buffer which is used when it calls draw arrays.

**Comment by jarikomppa** [comment]
I can't remember what the issue was exactly about; there were a bunch of
cleanup tasks related to draw_grid, and since draw_grid is based on
draw_rect (including the removal of ortho parameter), I posted issues on
all the cleanup tasks instead of performing the cleanup directly, as
discussed. It may be that this is also unnecessary like the removal of
ortho was.

**Comment by dj2** [comment]
K, closing for now then, we can reopen if we realize what this was in the future.
