### ISSUE TITLE
cleanup: draw_rect always ortho, has unused members

### ISSUE THREAD

**Issue by jarikomppa** [google/amber#804]
draw_rect has functions to set the ortho mode as well as member variable to set it on, but since the ortho mode is always set in the parser, these are not needed and could be removed.

**Comment by dj2** [comment]
In VkScript the `EnableOrtho` call is conditional on the `ortho` flag in the draw command. This calls either `EnableOrtho` or `EnablePatch`.  So this needs to be maintained.
