### ISSUE TITLE
Possible bug with array uniforms

### ISSUE THREAD

**Issue by afd** [google/amber#813]
I find that [this test](https://github.com/google/amber/files/4324900/arrays.txt) fails with both Intel Mesa and SwiftShader.

The fragment shader writes the colour vec4(A[3], 0.0, 0.0, 1.0), where A is an array of floats in a uniform buffer block.

In the Amber test, this buffer is initialized as follows:

```
BUFFER variant_A DATA_TYPE float DATA
 0.5 0.5 0.5 1.0 0.5
END
```

If this is the correct way to initialize a uniform block consisting of an array of 5 floats, then I believe the test should pass.

Instead, the framebuffer seems to be black.

**Comment by dj2** [comment]
My guess is this is a data layout issue. The UBO will end up in layout STD140, which for an array rounds up to 16 bytes. So, the UBO is looking at 80 bytes, but the `BUFFER` will default to STD430 which is going to give you 20 bytes.  (https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=159 rule 4)

If you put `STD140` on the `BUFFER`:

```
BUFFER variant_A DATA_TYPE float STD140 DATA
0.5 0.5 0.5 1.0 0.5
END
```

does it work?  Or, alternatively do:

```
BUFFER variantA DATA_TYPE float DATA
0.5 0 0 0
0.5 0 0 0
1.0 0 0 0
0.5 0 0 0
END
```

should also work I think.

**Comment by afd** [comment]
Thanks - both those solutions work, and indeed I now see that the shader contains `OpDecorate %12 ArrayStride 16`.
