### ISSUE TITLE
Wrong count for triangle list in example

### ISSUE THREAD

**Issue by afd** [google/amber#819]
An example in the AmberScript documentation contains the line:

`RUN kGraphicsPipeline DRAW_ARRAY AS TRIANGLE_LIST START_IDX 0 COUNT 24`

with the intention of providing 8 triangles, each with 3 vertices.  It seems that the tool expects COUNT to be the number of triangles here, so 24 should be changed to 8.

**Comment by asuonpaa** [comment]
I don't know about the documentation, but Amber clearly expects COUNT to be the number of vertices. This can be seen in the example files under test/cases. This matches with the Vulkan draw calls which also operate with the number of vertices and not primitives.

**Comment by afd** [comment]
Thanks for clarifying.
