### ISSUE TITLE
Addition to instanced draw (amber script)

### ISSUE THREAD

**Issue by ilkkasaa** [google/amber#870]
For instanced drawing it would be very useful to be able to define vertex input rate for vertex buffer bindings: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkVertexInputRate.html

I propose the amber script syntax to be something like: 
```groovy
PIPELINE ...
  VERTEX_DATA {buffer_name} LOCATION _val_ RATE {vertex|instance} (default vertex)
...
END 
```

**Comment by asuonpaa** [comment]
This is not as trivial as it seems. The input rate is defined per binding and not per location. Currently Amber has only binding 0 enabled and all locations has this binding. There are multiple TODOs in the code saying we should support multiple bindings for vertex data. I suppose this serves as a motivation to do that.

**Comment by asuonpaa** [comment]
Amber interleaves the vertex data automatically to a single Vulkan buffer, which is probably the reason only one binding is used. This means currently the user has no choice of manually adding interleaved data to a single Amber buffer and the input rate cannot be controlled per Amber buffer.

I believe a better option is to use a separate binding for each Amber buffer bound as vertex data. This change would happen under the hood with no changes needed to Amber script. We could also allow manual data interleaving in an Amber buffer when the same buffer is bound to multiple locations in the same pipeline. Amber buffers would restrict this to a single format so I don't know if that would be useful in many cases, but it's better than nothing.

With these changes the original syntax suggestion for RATE would be possible to implement.

**Comment by asuonpaa** [comment]
PR here: https://github.com/google/amber/pull/871
Interleaving vertex data inside Amber buffers can be done as a separate task if needed.
