### ISSUE TITLE
Assertion using default sampler values

### ISSUE THREAD

**Issue by alan-baker** [google/amber#927]
I have some amber tests that use samplers for 2D values. The amberscript docs indicate that `ADDRESS_MODE_W` is optional; however it default to `kUnknown`.  When this is translated to Vulkan, it picks `MIRROR_CLAMP_TO_EDGE` in release and asserts in debug. A similar issue exists for border color. I'd suggest just removing the assertion. My tests are ok when I do that.

**Comment by dj2** [comment]
@asuonpaa I believe you added the sampler support originally, can you take a look at this please?

**Comment by asuonpaa** [comment]
Sure I'll have a look.

**Comment by asuonpaa** [comment]
@alan-baker I'm not sure how you're getting kUnknown as a default address mode. Mine is defaulting to kRepeat which happens in Sampler constructor:

```
 private:
  std::string name_;
  FilterType min_filter_ = FilterType::kNearest;
  FilterType mag_filter_ = FilterType::kNearest;
  FilterType mipmap_mode_ = FilterType::kNearest;
  AddressMode address_mode_u_ = AddressMode::kRepeat;
  AddressMode address_mode_v_ = AddressMode::kRepeat;
  AddressMode address_mode_w_ = AddressMode::kRepeat;
  BorderColor border_color_ = BorderColor::kFloatTransparentBlack;
```

Can you show how you're specifying the sampler in your Amber script?

**Comment by alan-baker** [comment]
I think I found the cause of this and will post a PR. When the Vulkan engine adds a buffer descriptor for an image, it attempts to add a sampler for both combined sampled images (good) and sampled images (bad). In the latter case this leads generating a garbage sampler.
