### ISSUE TITLE
Amber ignores name and always uses "main" causing breakage

### ISSUE THREAD

**Issue by seanbaxter** [google/amber#933]
https://gist.github.com/seanbaxter/c5311a9b7b950fad1d8bade4db395fa0

I took compute_mat2x2.amber from the tests and changed the shader name to "my_shader" now it breaks.

**Comment by dj2** [comment]
The `name` in the `SHADER` line is used to link to the `ATTACH` command, not the name of the entry point inside the shader. You have to use the `ATTACH kVertexShader ENTRY_POINT main` version to change the entry point name.
