### ISSUE TITLE
Unable to create vulkan instance

### ISSUE THREAD

**Issue by DerZc** [google/amber#938]
hello,

when i run amber with testcase and vulkan as backend, I get the error "Unable to create vulkan instance", how can I fix that?

thank you

**Comment by dj2** [comment]
This means we were not able to correctly setup Vulkan. If you run the `vulkaninfo` program does it work correctly? Usually when this happens I check to make sure the various vulkan env variables (assuming your on Linux) are setup correctly. Namely, `VK_ICD_FILENAMES` and `VK_LAYER_PATH` need to be setup correctly.

**Comment by DerZc** [comment]
Thank you for your answer. I have solved that my GPU do not support vulkan. I have try on another GPU, but VK_ICD_FILENAMES is error, it should at /usr/share/vulkan/icd.d/, I get this from https://vulkan.lunarg.com/doc/sdk/1.2.162.1/linux/getting_started.html[https://vulkan.lunarg.com/doc/sdk/1.2.162.1/linux/getting_started.html]
![image](https://user-images.githubusercontent.com/34330257/104937490-ca860e80-59e8-11eb-8434-ad08e0804db8.png)

**Comment by dj2** [comment]
I believe the variable needs to point at the `json` file, not the directory that contains the file.

**Comment by DerZc** [comment]
yes, it should point at the json file, but this file not at vulkansdk directory as readme
![image](https://user-images.githubusercontent.com/34330257/104938887-ac211280-59ea-11eb-8361-6a6f9d8287a4.png)

**Comment by dj2** [comment]
It would depend on where your driver put the file, so you'll need to go lookup how your driver sets things up. I don't know offhand where the file would be on your system. Sorry.

Can this bug be closed, it sounds like this isn't an Amber issue?

**Comment by DerZc** [comment]
ok, you can close, thank you very much

**Comment by dj2** [comment]
Thanks, I hope you get things sorted.
