### ISSUE TITLE
Add checking Vulkan validation layer errors in kokoro test

### ISSUE THREAD

**Issue by jaebaek** [google/amber#96]
For integration tests, we must check Vulkan validation layer errors too.
I think we should use [LunarG validation layer](https://vulkan.lunarg.com/doc/view/1.1.73.0/windows/validation_layers.html) for kokoro tests.

**Comment by dj2** [comment]
The kokoro bots don't run any vulkan as vulkan isn't available on the bots. If we can figure out how to test GPU code, we can look into this then, but until then there is nothing to do here.
