### ISSUE TITLE
buffer_array

### ISSUE THREAD

**Issue by normrubin** [google/amber#991]
I'm having trouble understanding how to use BUFFER_ARRAY 
I was expecting something like 
buffer a dim_2d
buffer b dim_2d
bind buffer_array a, b  descriptor set 0 binding 0

would generate a 2darray object with 2 levels

is there an example or some more doc on how this is supposed to be used?

**Comment by dj2** [comment]
There are a couple example files showing `BUFFER_ARRAY` usage:

* https://github.com/google/amber/blob/8797ee109e7a6ea4d1f58f387f757545fa35325b/tests/cases/compute_descriptor_array_ssbo.amber
* https://github.com/google/amber/blob/8797ee109e7a6ea4d1f58f387f757545fa35325b/tests/cases/compute_descriptor_array_storagetexelbuffer.amber

Do those help?

**Comment by normrubin** [comment]
thanks just what i needed 
buffer_array is supposed to be for things like an array of 2d buffers not a single object of type 2darray

I'm trying to run some shaders that use cube and cubearray  textures -  I'll see if I can figure out  where i need to make changes in the amber code- But I expect I'll have some questions 

Norm

**Comment by dj2** [comment]
K, I'm going to close this as resolved. Let us know if you have further questions.
